#!/usr/bin/env bash
# LLDAP Provider Configuration

PROVIDER_NAME="lldap"
PROVIDER_DISPLAY_NAME="Light LDAP"
PROVIDER_DESCRIPTION="A lightweight LDAP server with a modern web interface"
PROVIDER_DOCKER_IMAGE="${LLDAP_DOCKER_IMAGE:-lldap/lldap:stable}"
PROVIDER_LDAP_PORT="${LLDAP_LDAP_PORT:-3890}"
PROVIDER_WEB_PORT="${LLDAP_WEB_PORT:-17170}"
PROVIDER_REQUIRES_NETWORK=true
PROVIDER_SUPPORTS_GROUPS=true
PROVIDER_SUPPORTS_GRAPHQL=true
